@ParkManager_HostAddress = http://localhost:32770

### Get all establishments
GET {{ParkManager_HostAddress}}/api/establishment
Accept: application/json

###

### Get establishment by ID
GET {{ParkManager_HostAddress}}/api/establishment/1f74068d-6503-4b1b-a99a-77f89a91170e
Accept: application/json

###

### Create a new establishment
POST {{ParkManager_HostAddress}}/api/establishment
Content-Type: application/json
Accept: application/json
{
  "name": "Sample Establishment",
  "cnpj": "12945678910129",
  "city": "São Paulo",
  "state": "SP",
  "street": "129 Main St",
  "number": "85",
  "complement": "Casa Azul",
  "zipCode": "37950000",
  "phone": "555881284",
  "motorcyclesParkingSpaces": 3,
  "carsParkingSpaces": 4
}

###

### Update an existing establishment
PUT {{ParkManager_HostAddress}}/api/establishment/1f74068d-6503-4b1b-a99a-77f89a91170e
Content-Type: application/json
Accept: application/json

{
  "name": "Sample Establishment",
  "cnpj": "12945678910129",
  "city": "São Paulo",
  "state": "SP",
  "street": "129 Main St",
  "number": "85",
  "complement": "Casa Azul",
  "zipCode": "37950000",
  "phone": "555881284",
  "motorcyclesParkingSpaces": 3,
  "carsParkingSpaces": 10
}

###

### Delete an establishment
DELETE {{ParkManager_HostAddress}}/api/establishment/4a4e2fd4-d113-4a6a-9b50-8158318f5c3f
Accept: application/json

###

### Entry A Vehicle
POST {{ParkManager_HostAddress}}/api/establishment/entry
Content-Type: application/json
Accept: application/json
{
  "establishmentId": "789de395-f8cc-4ac8-9288-2301f817e35e",
  "vehicleId": "2d0c90a7-a4fe-4255-85fa-f3188e01b4ab"
}

  ### Exit A Vehicle
POST {{ParkManager_HostAddress}}/api/establishment/exit
Content-Type: application/json
Accept: application/json
{
  "establishmentId": "789de395-f8cc-4ac8-9288-2301f817e35e",
  "vehicleId": "2d0c90a7-a4fe-4255-85fa-f3188e01b4ab"
}


### Get establishment report
GET {{ParkManager_HostAddress}}/api/establishment/789de395-f8cc-4ac8-9288-2301f817e35e/total-summary
Accept: application/json

###

  
  ### Get establishment daily report
GET {{ParkManager_HostAddress}}/api/establishment/789de395-f8cc-4ac8-9288-2301f817e35e/daily-summary/2025-06-05
Accept: application/json

###