@ParkManager_HostAddress = http://localhost:5000

### Get all establishments
GET {{ParkManager_HostAddress}}/api/establishment
Accept: application/json

###

### Get establishment by ID
GET {{ParkManager_HostAddress}}/api/establishment/789de395-f8cc-4ac8-9288-2301f817e35e
Accept: application/json

###

### Create a new establishment
POST {{ParkManager_HostAddress}}/api/establishment
Content-Type: application/json
Accept: application/json
{
  "name": "Sample Establishment",
  "cnpj": "12945678910129",
  "city": "São Paulo",
  "state": "SP",
  "street": "129 Main St",
  "number": "85",
  "complement": "Casa Azul",
  "zipCode": "37950000",
  "phone": "555881284",
  "motorcyclesParkingSpaces": 0,
  "carsParkingSpaces": 0
}

###

### Update an existing establishment
PUT {{ParkManager_HostAddress}}/api/establishment/f043b410-c9e8-434f-9aba-299cf98126e3
Content-Type: application/json
Accept: application/json

{
  "name": "Sample Establishment",
  "cnpj": "12945678910129",
  "city": "São Paulo",
  "state": "SP",
  "street": "129 Main St",
  "number": "85",
  "complement": "Casa Azul",
  "zipCode": "37950000",
  "phone": "555881284",
  "motorcyclesParkingSpaces": 3,
  "carsParkingSpaces": 15
}

###

### Delete an establishment
DELETE {{ParkManager_HostAddress}}/api/establishment/f043b410-a9e8-434f-9aba-299cf98126e3
Accept: application/json

###

### Entry A Vehicle
POST {{ParkManager_HostAddress}}/api/establishment/entry
Content-Type: application/json
Accept: application/json
{
  "establishmentId": "789de395-f8cc-4ac8-9288-2301f817e35e",
  "vehicleId": "2d0c90a7-a4fe-4255-85fa-f3188e01b4ab"
}

  ### Exit A Vehicle
POST {{ParkManager_HostAddress}}/api/establishment/exit
Content-Type: application/json
Accept: application/json
{
  "establishmentId": "789de395-f8cc-4ac8-9288-2301f817e35e",
  "vehicleId": "2d0c90a7-a4fe-4255-85fa-f3188e01b4ab"
}


### Get establishment report
GET {{ParkManager_HostAddress}}/api/establishment/789de395-f8cc-4ac8-9288-2301f817e35e/total-summary
Accept: application/json

###

  
  ### Get establishment daily report
GET {{ParkManager_HostAddress}}/api/establishment/789de395-f8cc-4ac8-9288-2301f817e35e/daily-summary/2025-06-05
Accept: application/json

###